import type { Chapter } from "./types"

export const PROJEKTMANAGEMENT_CHAPTERS: Chapter[] = [
  {
    id: 1,
    fr: "Bases du management de projet",
    de: "Projektmanagement Basics",
    lang: "none",
    hasCode: false,
    klausurRelevant: true,
    concepts: [
      "Projekt", "Projektmanagement", "magisches Dreieck", "Restriktionen",
      "Scope/Zeit/Kosten", "Prozessgruppen (PMI)", "Wissensgebiete",
      "Planungsprozess", "Projektorganisation", "Stakeholder",
      "Initiierung/Planung/Ausführung/Überwachung/Abschluss",
    ],
    summary: "Ein Projekt ist ein temporäres, einmaliges Vorhaben mit klarem Ziel, Zeitrahmen und Budget. Das magische Dreieck: Scope (Inhalt/Umfang), Zeit und Kosten - Änderung einer Größe beeinflusst die anderen. PMI-Prozessgruppen: Initiierung (I), Planung (P), Ausführung (E), Überwachung & Steuerung (M&C), Abschluss (C). 10 Wissensgebiete: Integration, Scope, Zeit, Kosten, Qualität, Personal, Kommunikation, Risiko, Beschaffung, Stakeholder. Projektmanager trägt Gesamtverantwortung für Zielerreichung.",
  },
  {
    id: 2,
    fr: "Intégration du projet",
    de: "Projektintegration",
    lang: "none",
    hasCode: false,
    klausurRelevant: true,
    concepts: [
      "Projektauftrag", "Business Case", "Leistungsbeschreibung",
      "Projektmanagementplan", "Change Control", "Änderungsantrag",
      "Projektabschluss", "Lessons Learned", "Projektintegration",
      "Projektskizze", "Projektauswahl",
    ],
    summary: "Projektintegration = wichtigste Aufgabe des PM, alle Teilbereiche zusammenführen. 5 Schritte: (1) Projektauftrag entwickeln (Business Case + Leistungsbeschreibung -> Project Charter). (2) PM-Plan entwickeln. (3) Projektarbeit führen. (4) Change Control durchführen: Änderungsanträge bewerten, genehmigen/ablehnen, integrieren. (5) Projekt schließen (Lessons Learned, Abschlussdokumentation). Projektskizze = kompaktes Dokument mit Ziel, Scope, Budget, Zeitrahmen, Risiken.",
  },
  {
    id: 3,
    fr: "Gestion du périmètre (Scope)",
    de: "Scope Management / PSP",
    lang: "none",
    hasCode: false,
    klausurRelevant: true,
    concepts: [
      "PSP", "Projektstrukturplan", "WBS", "Work Breakdown Structure",
      "Arbeitspaket", "Teilaufgabe", "Bottom-Up", "Top-Down",
      "Scope Baseline", "Scope Creep", "Anforderungen erheben",
      "Brainstorming", "Scope definieren", "Deliverable",
    ],
    summary: "Scope Management definiert WAS das Projekt liefert. PSP (Projektstrukturplan) = WBS (Work Breakdown Structure): hierarchische Zerlegung des Projekts in Arbeitspakete. Top-Down: vom Gesamtprojekt zu Arbeitspaketen. Bottom-Up: Arbeitspakete zuerst, dann zusammenfassen. 100%-Regel: PSP muss alle Lieferergebnisse vollständig abbilden. Arbeitspaket = kleinste Einheit, schätzbar und zuweisbar. Scope Creep = unkontrollierte Ausweitung des Scopes. Anforderungen erheben via Brainstorming, Interviews, Nominal Group Technique.",
  },
  {
    id: 4,
    fr: "Gestion du temps",
    de: "Zeitmanagement / Netzplan / Gantt",
    lang: "none",
    hasCode: false,
    klausurRelevant: true,
    concepts: [
      "PERT", "Drei-Punkt-Schätzung", "optimistisch/wahrscheinlich/pessimistisch",
      "Netzplan", "Vorgangsknoten", "kritischer Pfad", "Puffer",
      "Gantt-Diagramm", "Aktivitätenliste", "Vorgänger/Nachfolger",
      "Meilenstein", "Kompressionstechniken", "Crashing", "Fast Tracking",
      "Gesamtpuffer", "freier Puffer",
    ],
    summary: "PERT Drei-Punkt-Schätzung: (Optimistisch + 4xWahrscheinlich + Pessimistisch) / 6. Netzplan: Vorgänge als Knoten, Abhängigkeiten als Pfeile. Kritischer Pfad = längster Weg durch Netzplan, Gesamtpuffer = 0. Gesamtpuffer = spätester Anfang - frühester Anfang. Freier Puffer = frühester Anfang Nachfolger - frühestes Ende. Gantt-Diagramm: Balkendiagramm mit Zeit auf X-Achse. Crashing = mehr Ressourcen einsetzen (teurer). Fast Tracking = Aktivitäten parallel ausführen (riskanter).",
  },
  {
    id: 5,
    fr: "Gestion des coûts & Earned Value",
    de: "Kostenmanagement / Earned Value",
    lang: "none",
    hasCode: false,
    klausurRelevant: true,
    concepts: [
      "Kostenplanung", "Budget", "BAC", "Earned Value Methode",
      "EV", "PV", "AC", "CV", "SV", "CPI", "SPI",
      "EAC", "ETC", "Kostenabweichung", "Terminabweichung",
      "PERT Kostenabschätzung", "Bottom-Up-Schätzung",
    ],
    summary: "Earned Value Methode (EVM): PV (Planned Value) = geplanter Wert der Arbeit. EV (Earned Value) = tatsächlich erbrachter Wert. AC (Actual Cost) = tatsächliche Kosten. CV (Cost Variance) = EV - AC (negativ = über Budget). SV (Schedule Variance) = EV - PV (negativ = hinter Plan). CPI (Cost Performance Index) = EV/AC (>1 = unter Budget). SPI (Schedule Performance Index) = EV/PV (>1 = voraus). EAC (Estimate at Completion) = BAC/CPI. BAC = Budget at Completion (Gesamtbudget).",
  },
  {
    id: 6,
    fr: "Gestion de la qualité",
    de: "Qualitätsmanagement",
    lang: "none",
    hasCode: false,
    klausurRelevant: false,
    concepts: [
      "Qualität", "Qualitätsplanung", "Qualitätssicherung", "Qualitätskontrolle",
      "Ishikawa-Diagramm", "Fishbone", "Ursache-Wirkung",
      "Qualitätskosten", "Konformitätskosten", "Nichtkonformitätskosten",
      "PDCA", "Plan-Do-Check-Act", "Six Sigma", "Kaizen",
    ],
    summary: "Qualität = Grad der Erfüllung von Anforderungen. 3 Prozesse: Qualität planen -> Qualitätssicherung durchführen -> Qualität kontrollieren. Ishikawa-Diagramm (Fishbone): Ursache-Wirkungs-Analyse, Hauptkategorien Mensch/Methode/Material/Maschine/Milieu/Messung. Qualitätskosten: Konformitätskosten (Prävention, Inspektion) vs. Nichtkonformitätskosten (Nacharbeit, Garantie). PDCA-Zyklus: Plan -> Do -> Check -> Act (kontinuierliche Verbesserung).",
  },
  {
    id: 7,
    fr: "Gestion des risques",
    de: "Risikomanagement / FMEA / EMV",
    lang: "none",
    hasCode: false,
    klausurRelevant: true,
    concepts: [
      "Risikoregister", "FMEA", "Failure Mode and Effects Analysis",
      "Eintrittswahrscheinlichkeit", "Auswirkung", "Risikobewertung",
      "EMV", "monetärer Erwartungswert", "Risikoidentifikation",
      "Risikomatrix", "Risikovermeidung", "Risikominderung",
      "Risikoübertragung", "Risikoakzeptanz", "Chancen vs. Risiken",
    ],
    summary: "Risikoregister = Liste aller identifizierten Risiken mit Wahrscheinlichkeit, Auswirkung, Maßnahmen. FMEA (Failure Mode and Effects Analysis): Risikobewertung durch Eintrittswahrscheinlichkeit x Schweregrad x Entdeckbarkeit = RPZ (Risikoprioritätszahl). EMV (Erwarteter Monetärer Wert) = Eintrittswahrscheinlichkeit x monetäre Auswirkung. Strategien: Vermeidung (eliminieren), Minderung (reduzieren), Übertragung (versichern), Akzeptanz (hinnehmen). Chancen: ausnutzen, steigern, teilen, akzeptieren.",
  },
  {
    id: 8,
    fr: "Gestion des parties prenantes",
    de: "Stakeholder Management",
    lang: "none",
    hasCode: false,
    klausurRelevant: true,
    concepts: [
      "Stakeholder", "Macht-Interesse-Raster", "Einfluss-Interesse-Matrix",
      "Salienzmodell", "Macht", "Legitimität", "Dringlichkeit",
      "Stakeholderregister", "Stakeholderanalyse",
      "Stakeholderengagement", "Engagement-Level",
    ],
    summary: "Stakeholder = alle Personen/Gruppen mit Einfluss auf oder Interesse am Projekt. Macht-Interesse-Raster: 4 Quadranten: (1) Enge Zusammenarbeit (hohe Macht, hohes Interesse). (2) Zufrieden stellen (hohe Macht, geringes Interesse). (3) Informieren (geringe Macht, hohes Interesse). (4) Beobachten (geringe Macht, geringes Interesse). Salienzmodell: 3 Dimensionen - Macht, Legitimität, Dringlichkeit. Saliente Stakeholder haben alle 3. Stakeholderregister dokumentiert Name, Interesse, Einfluss, Strategie.",
  },
  {
    id: 9,
    fr: "Gestion des ressources humaines",
    de: "Personalmanagement / RACI",
    lang: "none",
    hasCode: false,
    klausurRelevant: true,
    concepts: [
      "RACI", "Responsible", "Accountable", "Consulted", "Informed",
      "Ressourcenhistogramm", "Personalplan", "Teambildung",
      "Forming", "Storming", "Norming", "Performing",
      "Konfliktmanagement", "Motivation", "Führungsstile",
    ],
    summary: "RACI-Matrix: Responsible (wer macht es), Accountable (wer ist verantwortlich, nur EINER!), Consulted (wer wird befragt), Informed (wer wird informiert). Ressourcenhistogramm: Balkendiagramm zeigt Ressourceneinsatz über Zeit -> erkennt Über-/Unterlastung. Teambildungsphasen (Tuckman): Forming (Kennenlernen) -> Storming (Konflikte) -> Norming (Regeln etablieren) -> Performing (Hochleistung). Projektmanager nutzt Führungsstile situativ.",
  },
  {
    id: 10,
    fr: "Gestion de la communication",
    de: "Kommunikationsmanagement",
    lang: "none",
    hasCode: false,
    klausurRelevant: false,
    concepts: [
      "Kommunikationsplan", "Kommunikationskanäle",
      "Formel Kommunikationskanäle", "Sender-Empfänger-Modell",
      "Kommunikationshürden", "Berichtswesen",
      "Pyramidenkommunikation", "aktives Zuhören",
    ],
    summary: "Anzahl Kommunikationskanäle: n x (n-1) / 2, wobei n = Anzahl Personen. Kommunikationsplan: Wer erhält welche Information, wie oft, in welchem Format. Sender-Empfänger-Modell: Nachricht -> Kodierung -> Kanal -> Dekodierung -> Empfänger -> Feedback. Kommunikationshürden: Sprache, Kultur, Rauschen, fehlende Rückkopplung. Pyramidenkommunikation: Kernaussage zuerst, dann Details (Executive Summary-Prinzip).",
  },
  {
    id: 11,
    fr: "Management de projet agile / SCRUM",
    de: "Agiles Projektmanagement - SCRUM",
    lang: "none",
    hasCode: false,
    klausurRelevant: true,
    concepts: [
      "Agil", "SCRUM", "Wasserfall", "Sprint", "Product Backlog",
      "Sprint Backlog", "Product Owner", "Scrum Master", "Entwicklungsteam",
      "Daily Scrum", "Sprint Review", "Sprint Retrospektive",
      "User Story", "Velocity", "Burndown Chart", "Definition of Done",
      "Empirismus", "Transparenz", "Inspektion", "Anpassung",
    ],
    summary: "SCRUM vs. Wasserfall: Wasserfall = sequentiell, SCRUM = iterativ/inkrementell. SCRUM-Rollen: Product Owner (Produktvision, Backlog priorisieren), Scrum Master (Coach, Hindernisse beseitigen), Entwicklungsteam (selbstorganisiert, 3-9 Personen). SCRUM-Artefakte: Product Backlog (priorisierte Anforderungsliste), Sprint Backlog (Aufgaben im aktuellen Sprint), Inkrement (fertiges Produktteil). SCRUM-Events: Sprint (1-4 Wochen), Daily Scrum (15 Min täglich), Sprint Review, Sprint Retrospektive. User Story: 'Als [Rolle] möchte ich [Funktion], damit [Nutzen].'",
  },
  {
    id: 12,
    fr: "Management de projet interculturel",
    de: "Interkulturelles Projektmanagement",
    lang: "none",
    hasCode: false,
    klausurRelevant: false,
    concepts: [
      "Kulturdimensionen", "Hofstede", "Machtdistanz", "Individualismus",
      "Unsicherheitsvermeidung", "Langzeitorientierung",
      "interkulturelle Kompetenz", "Stereotype", "kulturelle Unterschiede",
      "High-Context/Low-Context",
    ],
    summary: "Interkulturelles PM: Kulturelle Unterschiede beeinflussen Kommunikation, Entscheidungsfindung, Führung und Projektarbeit. Hofstede-Kulturdimensionen: Machtdistanz (Akzeptanz von Hierarchie), Individualismus vs. Kollektivismus, Maskulinität vs. Femininität, Unsicherheitsvermeidung, Langzeitorientierung. High-Context (implizit, Kontext wichtig, z.B. Japan) vs. Low-Context (explizit, direkt, z.B. Deutschland). Interkulturelle Kompetenz: Wissen, Empathie, Flexibilität, Kommunikationsfähigkeit.",
  },
  {
    id: 13,
    fr: "Gestion du changement",
    de: "Change Management",
    lang: "none",
    hasCode: false,
    klausurRelevant: false,
    concepts: [
      "Change Management", "Carta des Change Management",
      "Kotters 8 Stufen", "Kotters 8 Fehler",
      "Widerstand gegen Veränderung", "Change-Kurve",
      "Führungskoalition", "Vision kommunizieren",
      "Quick Wins", "Unternehmenskultur",
    ],
    summary: "Change Management = strukturierter Ansatz zur Steuerung von Veränderungen. Carta des CM (Doppler & Lauterburg): 8 Prinzipien: Zielorientierung, keine Maßnahme ohne Diagnose, ganzheitliches Denken, Beteiligung der Betroffenen, Hilfe zur Selbsthilfe, Prozessorientierung, lebendige Kommunikation, sorgfältige Schlüsselpersonenwahl. Kotters 8-Stufen: (1) Dringlichkeit erzeugen, (2) Führungskoalition aufbauen, (3) Vision entwickeln, (4) Vision kommunizieren, (5) Hindernisse beseitigen, (6) Kurzfristige Erfolge erzielen, (7) Erfolge konsolidieren, (8) Wandel in Kultur verankern.",
  },
]
